blueprint:
  name: Floor heat — two-state (policy-driven + min keep temp)
  description: >
    Drives a floor-heat thermostat between two states using an external
    Energy Saving Policy boolean (ON = save, OFF = don't care).
    Policy link: https://gist.github.com/ohlsont/abbc5321378594d4ada8dfb2707299d4
    • When policy = ON (save): set soft-off temperature (device min or override)
    • When policy = OFF (don't care): set comfort temperature (optionally only during schedule = ON)
    • NEW: When policy = OFF and comfort schedule = OFF, optionally maintain a minimum "keep" temperature.
    Priority: Policy → (optional) Comfort schedule. Includes debounce.
  domain: automation

  input:
    climate_entity:
      name: Thermostat (climate.*)
      selector: { entity: { domain: climate } }

    energy_saving_boolean:
      name: Energy saving boolean (from Energy Saving Policy)
      description: >
        The input_boolean managed by the Energy Saving Policy (ON = save energy,
        OFF = don't care). See:
        https://gist.github.com/ohlsont/72e2dc6ffb4d211e74da4f26a89f2e4a
      selector:
        entity:
          domain: input_boolean
          multiple: false

    # Comfort target when ON
    comfort_temp_c:
      name: Comfort setpoint when ON (°C)
      description: Used whenever heating is enabled (policy OFF and schedule allows).
      default: 22
      selector: { number: { min: 5, max: 35, step: 0.5, mode: box } }

    prefer_preset_manual:
      name: Prefer "manual" preset if available
      description: If the thermostat supports a 'manual' preset, use it when enabling heating.
      default: true
      selector: { boolean: {} }

    hvac_mode_when_on:
      name: Fallback HVAC mode when enabling (if no 'manual' preset)
      description: One of the climate's supported hvac_modes, e.g. 'heat' or 'auto'
      default: "heat"
      selector:
        select:
          options:
            - "heat"
            - "auto"
            - "heat_cool"
            - "off"

    # Soft-off target when policy says SAVE (OFF state)
    soft_off_temp_override_c:
      name: (Optional) Soft-off temperature override (°C)
      description: Leave empty to use device min_temp automatically.
      default: ""
      selector: { text: {} }

    # NEW: minimum keep temperature when policy OFF and schedule OFF
    min_keep_temp_c:
      name: (Optional) Minimum keep temperature when policy OFF (°C)
      description: >
        When energy saving is OFF and the comfort schedule is OFF (or not set),
        the thermostat will target at least this temperature.
        Leave empty to behave like soft-off in those periods.
      default: ""
      selector: { text: {} }

    # Comfort schedule that ALLOWS heat during policy OFF windows
    comfort_schedule:
      name: (Optional) Comfort schedule entity
      description: A Schedule helper like schedule.floor_heat_comfort (ON = allow heat)
      default: ""
      selector:
        entity:
          multiple: false

    # Safety / debouncing
    min_switch_interval_min:
      name: Minimum minutes between state changes
      default: 15
      selector: { number: { min: 0, max: 120, step: 1, mode: slider } }

mode: restart
max_exceeded: silent

variables:
  climate_ent: !input climate_entity
  es_bool: !input energy_saving_boolean
  comfort_temp_c: !input comfort_temp_c
  prefer_preset_manual: !input prefer_preset_manual
  hvac_mode_when_on: !input hvac_mode_when_on
  soft_off_temp_override_c: !input soft_off_temp_override_c
  min_keep_temp_c: !input min_keep_temp_c       # NEW
  comfort_schedule: !input comfort_schedule
  min_switch_interval_min: !input min_switch_interval_min

trigger:
  - platform: state
    entity_id: !input energy_saving_boolean
  - platform: state
    entity_id: !input comfort_schedule
  - platform: state
    entity_id: !input climate_entity
    attribute: temperature
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - variables:
      policy_saving: "{{ is_state(es_bool, 'on') }}"  # ON = save → go soft-off

      # Determine min and current temps
      dev_min: "{{ state_attr(climate_ent, 'min_temp') | float(5) }}"
      soft_off_target: >-
        {% set o = soft_off_temp_override_c %}
        {{ (o | float(o)) if (o | string) | length > 0 else dev_min }}

      cur_temp: "{{ state_attr(climate_ent, 'temperature') | float(999) }}"

      # NEW: derived min-keep temperature
      min_keep_temp_defined: "{{ (min_keep_temp_c | string) | length > 0 }}"
      min_keep_temp: >-
        {% if min_keep_temp_defined %}
          {{ min_keep_temp_c | float(min_keep_temp_c) }}
        {% else %}
          {{ soft_off_target }}
        {% endif %}

      # Schedule gating (optional)
      schedule_defined: "{{ comfort_schedule is string and comfort_schedule != '' }}"
      schedule_on: >-
        {% if schedule_defined %}{{ is_state(comfort_schedule, 'on') }}{% else %}true{% endif %}

      # Debounce based on last thermostat change
      now_ts: "{{ now().timestamp() }}"
      last_changed_ts: "{{ states[climate_ent].last_changed.timestamp() if states[climate_ent] is defined else 0 }}"
      enough_time_passed: "{{ (now_ts - last_changed_ts) >= (min_switch_interval_min | int(15) * 60) }}"

      # Robust HVAC mode fallback
      supported_hvac: "{{ state_attr(climate_ent,'hvac_modes') | default([], true) | map('lower') | list }}"
      hvac_mode_final: >-
        {% set cand = (hvac_mode_when_on | string) %}
        {% set sup = supported_hvac %}
        {% if cand in sup %}{{ cand }}
        {% elif 'heat' in sup %}heat
        {% elif 'auto' in sup %}auto
        {% elif 'heat_cool' in sup %}heat_cool
        {% elif sup | count > 0 %}{{ sup[0] }}
        {% else %}heat{% endif %}

      # NEW: single desired setpoint based on policy + schedule + min-keep
      # - Policy ON  → soft-off
      # - Policy OFF & schedule ON → comfort
      # - Policy OFF & schedule OFF & min_keep defined → min_keep
      # - Policy OFF & schedule OFF & no min_keep → soft-off
      desired_temp: >-
        {% if policy_saving %}
          {{ soft_off_target }}
        {% elif schedule_on %}
          {{ comfort_temp_c }}
        {% elif min_keep_temp_defined %}
          {{ min_keep_temp }}
        {% else %}
          {{ soft_off_target }}
        {% endif %}

      # Interpret desired_temp as "on" vs "soft-off"
      target_on: "{{ desired_temp > (soft_off_target + 0.2) }}"
      currently_soft_off: "{{ cur_temp <= (soft_off_target + 0.2) }}"
      need_temp_change: >-
        {% set cur = cur_temp | float(999) %}
        {% set des = desired_temp | float(999) %}
        {{ (cur - des) | abs > 0.05 }}

  - choose:
      # Need to go to an "ON" target (comfort or min-keep)
      - conditions:
          - condition: template
            value_template: "{{ target_on and (currently_soft_off or need_temp_change) and enough_time_passed }}"
        sequence:
          # Prefer preset 'manual' if supported when enabling / adjusting
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ prefer_preset_manual and 'manual' in (state_attr(climate_ent,'preset_modes') | default([], true) | map('lower') | list) }}
                sequence:
                  - service: climate.set_preset_mode
                    target: { entity_id: "{{ climate_ent }}" }
                    data: { preset_mode: manual }
            default:
              - service: climate.set_hvac_mode
                target: { entity_id: "{{ climate_ent }}" }
                data: { hvac_mode: "{{ hvac_mode_final }}" }

          - delay: "00:00:01"
          - service: climate.set_temperature
            target: { entity_id: "{{ climate_ent }}" }
            data:
              temperature: "{{ desired_temp }}"

          - service: logbook.log
            data:
              name: Floor heat
              message: >-
                → ON ({{ 'comfort' if schedule_on else 'min-keep' }} {{ desired_temp }}°C).
                Policy={{ 'OFF (don''t care)' if not policy_saving else 'ON (save energy)' }},
                Schedule={{ 'ON' if schedule_on else 'OFF' }}.

      # Need to go to soft-off
      - conditions:
          - condition: template
            value_template: "{{ (not target_on) and (not currently_soft_off) and enough_time_passed }}"
        sequence:
          # Optional: switch to manual preset if available so the setpoint sticks predictably
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ 'manual' in (state_attr(climate_ent,'preset_modes') | default([], true) | map('lower') | list) }}
                sequence:
                  - service: climate.set_preset_mode
                    target: { entity_id: "{{ climate_ent }}" }
                    data: { preset_mode: manual }
            default: []

          - delay: "00:00:01"
          - service: climate.set_temperature
            target: { entity_id: "{{ climate_ent }}" }
            data:
              temperature: "{{ soft_off_target }}"

          - service: logbook.log
            data:
              name: Floor heat
              message: >-
                → OFF (soft-off {{ soft_off_target }}°C).
                Policy={{ 'ON (save energy)' if policy_saving else 'OFF (don''t care)' }},
                Schedule={{ 'ON' if schedule_on else 'OFF' }}.
  # No action if target matches current state or debounce not satisfied