blueprint:
  name: Block heat — target calculator (saving mode)
  description: >
    Computes the saving-mode target temperature for Block Heat and writes it to
    an input_number helper for deterministic validation.

    Formula:
    - If outdoor >= warm shutdown: target = virtual temperature
    - Else: target = setpoint - saving cold offset
    - Target is clamped to control min/max before write.
  domain: automation

  input:
    section_policy:
      name: "Section — Policy"
      description: " "
      default: "Policy"
      selector:
        text:

    energy_saving_boolean:
      name: Policy — Energy saving boolean
      description: ON = save energy now, OFF = don't care
      selector:
        entity:
          domain: input_boolean
          multiple: false

    section_sensors:
      name: "Section — Sensors"
      description: " "
      default: "Sensors"
      selector:
        text:

    outdoor_temperature_sensor:
      name: Sensors — Outdoor temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    section_targets:
      name: "Section — Targets"
      description: " "
      default: "Targets"
      selector:
        text:

    target_saving_helper:
      name: Targets — Saving target helper (input_number)
      description: Helper that stores the computed saving target
      selector:
        entity:
          domain: input_number
          multiple: false

    section_control:
      name: "Section — Control"
      description: " "
      default: "Control"
      selector:
        text:

    heatpump_setpoint:
      name: Control — Heatpump setpoint (°C)
      default: 20
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    saving_cold_offset_c:
      name: Control — Saving cold offset (°C)
      description: Subtracted from setpoint when saving mode is active and it is cold outside
      default: 1
      selector:
        number:
          min: 0
          max: 6
          step: 0.1
          unit_of_measurement: "°C"

    virtual_temperature:
      name: Control — Virtual temperature (°C)
      description: Used when saving mode is active and outdoor is warm
      default: 20
      selector:
        number:
          min: 0
          max: 40
          step: 0.5
          unit_of_measurement: "°C"

    energy_saving_warm_shutdown_outdoor:
      name: Control — Warm shutdown threshold (°C)
      description: Saving mode writes virtual temperature when outdoor is above this threshold
      default: 7
      selector:
        number:
          min: -20
          max: 20
          step: 0.5
          unit_of_measurement: "°C"

    control_min_c:
      name: Control — Minimum control temperature (°C)
      default: 10
      selector:
        number:
          min: 0
          max: 25
          step: 0.5
          unit_of_measurement: "°C"

    control_max_c:
      name: Control — Maximum control temperature (°C)
      default: 26
      selector:
        number:
          min: 5
          max: 40
          step: 0.5
          unit_of_measurement: "°C"

    helper_write_delta_c:
      name: Control — Minimum helper write delta (°C)
      description: Only write helper when absolute delta is at least this value
      default: 0.05
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          unit_of_measurement: "°C"

mode: restart
max_exceeded: silent

variables:
  es_bool: !input energy_saving_boolean
  outdoor_temperature_sensor: !input outdoor_temperature_sensor
  target_saving_helper: !input target_saving_helper
  heatpump_setpoint: !input heatpump_setpoint
  saving_cold_offset_c: !input saving_cold_offset_c
  virtual_temperature: !input virtual_temperature
  energy_saving_warm_shutdown_outdoor: !input energy_saving_warm_shutdown_outdoor
  control_min_c: !input control_min_c
  control_max_c: !input control_max_c
  helper_write_delta_c: !input helper_write_delta_c

trigger:
  - platform: state
    entity_id: !input energy_saving_boolean
  - platform: state
    entity_id: !input outdoor_temperature_sensor
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - variables:
      outdoor_temp: "{{ states(outdoor_temperature_sensor) | float(default=none) }}"
      setpoint: "{{ heatpump_setpoint | float(20) }}"
      warm_shutdown: "{{ energy_saving_warm_shutdown_outdoor | float(7) }}"
      cold_offset: "{{ saving_cold_offset_c | float(1) }}"
      min_c: "{{ control_min_c | float(10) }}"
      max_c: "{{ control_max_c | float(26) }}"
      current_helper: "{{ states(target_saving_helper) | float(default=none) }}"
      target_unclamped: >-
        {% if outdoor_temp is number and outdoor_temp >= warm_shutdown %}
          {{ virtual_temperature | float(20) }}
        {% else %}
          {{ setpoint - cold_offset }}
        {% endif %}
      target: "{{ [max_c, [min_c, target_unclamped] | max] | min }}"

  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ target is number and
                 (current_helper is not number or
                  (target - current_helper) | abs >= (helper_write_delta_c | float(0.05))) }}
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input target_saving_helper
            data:
              value: "{{ target }}"
