blueprint:
  name: Block heat — final arbiter and writer
  description: >
    Final stage of Block Heat modular control.

    Reads policy state plus intermediate helper targets, applies precedence,
    clamps, and writes the final control number.

    Precedence:
    1) Policy ON  -> saving target helper
    2) Policy OFF + fallback active -> control minimum
    3) Policy OFF + fallback inactive -> comfort target helper

    This is the only Block Heat blueprint that writes to the control number.
  domain: automation

  input:
    section_policy:
      name: "Section — Policy"
      description: " "
      default: "Policy"
      selector:
        text:

    energy_saving_boolean:
      name: Policy — Energy saving boolean
      selector:
        entity:
          domain: input_boolean
          multiple: false

    fallback_active_boolean:
      name: Policy — Fallback active boolean
      selector:
        entity:
          domain: input_boolean
          multiple: false

    section_targets:
      name: "Section — Targets"
      description: " "
      default: "Targets"
      selector:
        text:

    target_saving_helper:
      name: Targets — Saving target helper (input_number)
      selector:
        entity:
          domain: input_number
          multiple: false

    target_comfort_helper:
      name: Targets — Comfort target helper (input_number)
      selector:
        entity:
          domain: input_number
          multiple: false

    target_final_helper:
      name: Targets — Final target helper (input_number)
      selector:
        entity:
          domain: input_number
          multiple: false

    section_control:
      name: "Section — Control"
      description: " "
      default: "Control"
      selector:
        text:

    control_number_entity:
      name: Control — Controllable sensor (MQTT number)
      description: Number entity consumed by the heatpump/PT100 emulation path
      selector:
        entity:
          domain: number
          integration: mqtt
          multiple: false

    control_min_c:
      name: Control — Minimum control temperature (°C)
      default: 10
      selector:
        number:
          min: 0
          max: 25
          step: 0.5
          unit_of_measurement: "°C"

    control_max_c:
      name: Control — Maximum control temperature (°C)
      default: 26
      selector:
        number:
          min: 5
          max: 40
          step: 0.5
          unit_of_measurement: "°C"

    control_write_delta_c:
      name: Control — Minimum write delta to control number (°C)
      description: Write to control number only if absolute delta is at least this value
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.01
          unit_of_measurement: "°C"

    helper_write_delta_c:
      name: Control — Minimum write delta to final helper (°C)
      description: Write to final helper only if absolute delta is at least this value
      default: 0.05
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          unit_of_measurement: "°C"

mode: restart
max_exceeded: silent

variables:
  es_bool: !input energy_saving_boolean
  fallback_active_boolean: !input fallback_active_boolean
  target_saving_helper: !input target_saving_helper
  target_comfort_helper: !input target_comfort_helper
  target_final_helper: !input target_final_helper
  control_number_entity: !input control_number_entity
  control_min_c: !input control_min_c
  control_max_c: !input control_max_c
  control_write_delta_c: !input control_write_delta_c
  helper_write_delta_c: !input helper_write_delta_c

trigger:
  - platform: state
    entity_id: !input energy_saving_boolean
  - platform: state
    entity_id: !input fallback_active_boolean
  - platform: state
    entity_id: !input target_saving_helper
  - platform: state
    entity_id: !input target_comfort_helper
  - platform: state
    entity_id: !input control_number_entity
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - variables:
      saving_target: "{{ states(target_saving_helper) | float(default=none) }}"
      comfort_target: "{{ states(target_comfort_helper) | float(default=none) }}"
      final_target_current: "{{ states(target_final_helper) | float(default=none) }}"
      control_current: "{{ states(control_number_entity) | float(default=none) }}"
      min_c: "{{ control_min_c | float(10) }}"
      max_c: "{{ control_max_c | float(26) }}"
      selected_unclamped: >-
        {% if is_state(es_bool, 'on') %}
          {% if saving_target is number %}
            {{ saving_target }}
          {% elif control_current is number %}
            {{ control_current }}
          {% else %}
            {{ min_c }}
          {% endif %}
        {% elif is_state(fallback_active_boolean, 'on') %}
          {{ min_c }}
        {% else %}
          {% if comfort_target is number %}
            {{ comfort_target }}
          {% elif control_current is number %}
            {{ control_current }}
          {% else %}
            {{ min_c }}
          {% endif %}
        {% endif %}
      target_final: "{{ [max_c, [min_c, selected_unclamped] | max] | min }}"

  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ target_final is number and
                 (final_target_current is not number or
                  (target_final - final_target_current) | abs >= (helper_write_delta_c | float(0.05))) }}
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input target_final_helper
            data:
              value: "{{ target_final }}"

  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ target_final is number and
                 (control_current is not number or
                  (target_final - control_current) | abs >= (control_write_delta_c | float(0.2))) }}
        sequence:
          - service: number.set_value
            target:
              entity_id: !input control_number_entity
            data:
              value: "{{ target_final }}"
