blueprint:
  name: Block heat — electric assist fallback manager
  description: >
    Manages a fallback-active boolean for Block Heat.

    Activation:
    - Policy must be OFF
    - Coldest comfort room must stay below (comfort target - trigger delta)
      for the configured trigger minutes
    - Cooldown since last trigger must be satisfied

    Deactivation:
    - Policy turns ON, or
    - Coldest comfort room recovers above (comfort target - release delta)
  domain: automation

  input:
    section_policy:
      name: "Section — Policy"
      description: " "
      default: "Policy"
      selector:
        text:

    energy_saving_boolean:
      name: Policy — Energy saving boolean
      selector:
        entity:
          domain: input_boolean
          multiple: false

    section_sensors:
      name: "Section — Sensors"
      description: " "
      default: "Sensors"
      selector:
        text:

    comfort_room_1_sensor:
      name: Sensors — Comfort room 1 temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    comfort_room_2_sensor:
      name: Sensors — Comfort room 2 temperature sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false

    section_helpers:
      name: "Section — Helpers"
      description: " "
      default: "Helpers"
      selector:
        text:

    fallback_active_boolean:
      name: Helpers — Fallback active boolean (input_boolean)
      selector:
        entity:
          domain: input_boolean
          multiple: false

    electric_fallback_last_trigger:
      name: Helpers — Last fallback trigger (input_datetime)
      selector:
        entity:
          domain: input_datetime
          multiple: false

    section_thresholds:
      name: "Section — Thresholds"
      description: " "
      default: "Thresholds"
      selector:
        text:

    comfort_target_c:
      name: Thresholds — Comfort target (°C)
      default: 22
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    electric_fallback_delta_c:
      name: Thresholds — Trigger delta below comfort target (°C)
      default: 0.5
      selector:
        number:
          min: 0
          max: 3
          step: 0.1
          unit_of_measurement: "°C"

    release_delta_c:
      name: Thresholds — Release delta below comfort target (°C)
      description: Fallback turns OFF once comfort_min reaches target - release_delta
      default: 0.1
      selector:
        number:
          min: 0
          max: 3
          step: 0.1
          unit_of_measurement: "°C"

    electric_fallback_minutes:
      name: Thresholds — Trigger delay (minutes)
      default: 30
      selector:
        number:
          min: 1
          max: 240
          step: 1
          unit_of_measurement: Minutes
          mode: slider

    electric_fallback_cooldown_minutes:
      name: Thresholds — Cooldown after trigger (minutes)
      default: 60
      selector:
        number:
          min: 0
          max: 360
          step: 1
          unit_of_measurement: Minutes
          mode: slider

mode: restart
max_exceeded: silent

variables:
  es_bool: !input energy_saving_boolean
  comfort_room_1_sensor: !input comfort_room_1_sensor
  comfort_room_2_sensor: !input comfort_room_2_sensor
  fallback_active_boolean: !input fallback_active_boolean
  electric_fallback_last_trigger: !input electric_fallback_last_trigger
  comfort_target_c: !input comfort_target_c
  electric_fallback_delta_c: !input electric_fallback_delta_c
  release_delta_c: !input release_delta_c
  electric_fallback_cooldown_minutes: !input electric_fallback_cooldown_minutes

trigger:
  - platform: state
    entity_id: !input energy_saving_boolean
  - platform: state
    entity_id: !input comfort_room_1_sensor
  - platform: state
    entity_id: !input comfort_room_2_sensor
  - platform: homeassistant
    event: start
  - platform: template
    id: arm_fallback
    value_template: >-
      {% set r1 = states(comfort_room_1_sensor) | float(default=none) %}
      {% set r2 = states(comfort_room_2_sensor) | float(default=none) %}
      {% set comfort_min = [r1, r2] | select('number') | list | min(default=none) %}
      {% set target = comfort_target_c | float(22) %}
      {% set delta = electric_fallback_delta_c | float(0.5) %}
      {% set last_ts = as_timestamp(states(electric_fallback_last_trigger)) | float(0) %}
      {% set now_ts = now().timestamp() %}
      {% set cooldown_ok = (now_ts - last_ts) >= (electric_fallback_cooldown_minutes | float(60) * 60) %}
      {{ is_state(es_bool, 'off') and
         (comfort_min is number) and
         comfort_min < (target - delta) and
         cooldown_ok and
         is_state(fallback_active_boolean, 'off') }}
    for:
      minutes: !input electric_fallback_minutes
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - variables:
      comfort_min: >-
        {% set r1 = states(comfort_room_1_sensor) | float(default=none) %}
        {% set r2 = states(comfort_room_2_sensor) | float(default=none) %}
        {{ [r1, r2] | select('number') | list | min(default=none) }}
      release_threshold: "{{ (comfort_target_c | float(22)) - (release_delta_c | float(0.1)) }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'arm_fallback' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input fallback_active_boolean
          - service: input_datetime.set_datetime
            target:
              entity_id: !input electric_fallback_last_trigger
            data:
              timestamp: "{{ now().timestamp() | int }}"

      - conditions:
          - condition: template
            value_template: >-
              {{ is_state(es_bool, 'on') and is_state(fallback_active_boolean, 'on') }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input fallback_active_boolean

      - conditions:
          - condition: template
            value_template: >-
              {{ is_state(es_bool, 'off') and is_state(fallback_active_boolean, 'on') and
                 (comfort_min is number) and comfort_min >= release_threshold }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input fallback_active_boolean
